package com.MDS2.ForoUal.Interfaz;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Opciones_Mensajes_Ventana extends VerticalLayout {
	protected Button crearMensaje;
	protected Button reportarMensaje;
	protected Label reportarMensajeMnj;
	protected Button responderMensaje;
	protected Label responderMensajeMnj;

	public Opciones_Mensajes_Ventana() {
		Design.read(this);
	}
}
