package com.MDS2.ForoUal.Interfaz;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_OtroPerfil_Ventana extends AbsoluteLayout {
	protected Panel perfil;
	protected Image fotoPerfil;
	protected Label userName;
	protected Label realName;
	protected Label email;
	protected Label descpription;
	protected Panel panelSuperior;
	protected Panel panelOpciones;
	protected VerticalLayout panelOpcionesLayout;
	protected HorizontalLayout reportado;
	protected Panel ultimosMensajes;

	public Ver_OtroPerfil_Ventana() {
		Design.read(this);
	}
}
