package com.MDS2.ForoUal.Interfaz;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizar_Mensaje_Ventana extends VerticalLayout {
	protected Image denuciado;
	protected Label texto;
	protected Button respuestaA;
	protected Video video;
	protected Image imagen1;
	protected Image imagen2;
	protected Image imagen3;
	protected Label creadorYFecha;
	protected HorizontalLayout meGustaLayout;
	protected Label numeroMeGusta;

	public Visualizar_Mensaje_Ventana() {
		Design.read(this);
	}
}
