package com.MDS2.ForoUal.Interfaz;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VIsualizar_temas_No_Reg_Ventana extends AbsoluteLayout {
	protected Panel listaTemas;
	protected Panel panelSuperior;

	public VIsualizar_temas_No_Reg_Ventana() {
		Design.read(this);
	}
}
