package com.MDS2.Foro_UAL.MainPanel;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Visualizar_Perfil extends AbsoluteLayout {
	protected VerticalLayout ultimosMensajes;
	protected Label descripcion;
	protected Image fotoPerfil;
	protected Label nombreUsuario;
	protected Label nombreReal;
	protected Label email;

	public Visualizar_Perfil() {
		Design.read(this);
	}
}
