package com.MDS2.Foro_UAL.popUp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PopUp_Panel extends AbsoluteLayout {
	protected Label titulo;
	protected Label descripcion;
	protected HorizontalLayout shortInput1_Parent;
	protected Label shortInput1_Name;
	protected TextField shortInput1;
	protected HorizontalLayout shortInput2_Parent;
	protected Label shortInput2_Name;
	protected TextField shortInput2;
	protected HorizontalLayout shortInput3_Parent;
	protected Label shortInput3_Name;
	protected TextField shortInput3;
	protected HorizontalLayout largeInput_Parent;
	protected Label largeInput_Name;
	protected TextField largeInput;

	public PopUp_Panel() {
		Design.read(this);
	}
}
