package com.MDS2.Foro_UAL.UserInterface;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class index_ventana extends AbsoluteLayout {
	protected Panel panelSuperior;
	protected Panel barraHerramientas;
	protected VerticalLayout barraHerramientasLayout;
	protected Panel panelCentral;
	protected Panel barraAmigos;

	public index_ventana() {
		Design.read(this);
	}
}
