package com.MDS2.ForoUal.Interfaz.Opciones;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Cambiar_Estado_Tema_Ventana extends VerticalLayout {
	protected Panel publicoPanel;
	protected Image publico;
	protected Panel privadoPanel;
	protected Image privado;
	protected Panel ocultoPanel;
	protected Image oculto;
	protected Panel borradoPanel;
	protected Image borrado;

	public Cambiar_Estado_Tema_Ventana() {
		Design.read(this);
	}
}
