package com.MDS2.ForoUal.Interfaz.Opciones;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Crear_Seccion_Ventana extends VerticalLayout {
	protected TextField nombre;
	protected TextField descripcion;
	protected Button cancelar;
	protected Button continuar;

	public Crear_Seccion_Ventana() {
		Design.read(this);
	}
}
